/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE eventsBaseService PLEASE EDIT ../events.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Events } from '../../domain/ng-rome_db/events';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../events.service.ts
 */

/*
 * SCHEMA DB events
 *
	{
		date: {
			type: 'Date'
		},
		description: {
			type: 'String'
		},
		name: {
			type: 'String'
		},
		place: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
	}
 *
 */
@Injectable()
export class EventsBaseService {

    private eventsCollection: AngularFirestoreCollection<Events>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.eventsCollection = afs.collection<Events>('events');
    }


    // CRUD METHODS

    /**
    * eventsService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Events): Promise<DocumentReference> {
        return this.eventsCollection.add(item);
    }

    /**
    * eventsService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.eventsCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * eventsService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): AngularFirestoreDocument<Events> {
        return this.afs.doc<Events>('events/' + id);
    }

    /**
    * eventsService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Events[]> {
        return this.afs.collection('events').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Events;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * eventsService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Events>, item: Events): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
